import { poppins } from './utils/fonts';
import "./globals.css";
import Providers from '../lib/features/provider';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${poppins}`}>
          <main className='font-poppins'>
            {children}
          </main>
        </body>
      </html>
    </Providers>    
  );
}
